import type { Metadata } from "next";
// import localFont from "next/font/local";
import "@/lib/globals.css";
import Navbar from "../components/Navbar";
import Sidenav from "../components/Sidenav";
import { Toaster } from "@/components/ui/sonner";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Recsys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#E0E7E9] relative`}
      >
        <Toaster />
        <Navbar/>
      
        <Sidenav/>
        <div className="w-full pt-[15%] md:pt-0  md:absolute z-30 md:right-0 md:top-[80px] md:w-[80%] ">
            {children}
        </div>
      </body>
    </html>
  );
}
