import type { Metadata } from "next";
import "@/lib/globals.css";
import Navbar from "../components/Navbar";
import Sidenav from "../components/Sidenav";
import { Toaster } from "@/components/ui/sonner";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "../components/convex-client-provider";
import { TeacherGuard } from "@/components/guards/teacher-guard";

export const metadata: Metadata = {
  title: "ERMS-teacher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <ConvexClientProvider>
        <html lang="en">
          <body
            className={`bg-[#E0E7E9] relative`}
          > 
            <TeacherGuard>
              <Toaster richColors />
              <Navbar/>
              <Sidenav/>
              <div className="w-full pt-[15%] md:pt-0  md:absolute z-30 md:right-0 md:top-[80px] md:w-[80%]">
                  {children}
              </div>
            </TeacherGuard>
          </body>
        </html>
      </ConvexClientProvider>
    </ConvexAuthNextjsServerProvider>
  );
}
